#!/bin/bash

# Update repository information
sudo apt update && sudo apt upgrade

sudo apt install aptitude

sudo aptitude -ry install libxmu-dev libssl-dev libgdal-dev libproj-dev git software-properties-common \
apt-transport-https wget python3-pip python3-venv python3-dev python3-setuptools \
zsh fonts-powerline net-tools curl unzip

# alacritty
sudo add-apt-repository ppa:aslatter/ppa -y
sudo apt install alacritty

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

## Oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

#starship
curl -sS https://starship.rs/install.sh | sh

#fnm
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell

# TheFuck
pip3 install thefuck --user

# Exa
cargo install exa

# Delta git differ
cargo install git-delta

# Zellij
cargo install zellij